CREATE TABLE users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR,
  username VARCHAR,
  email VARCHAR,
  telephone VARCHAR,
  company_id INT,
  created_at TIMESTAMP DEFAULT current_timestamp
);

CREATE TABLE companies (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name VARCHAR,
  email VARCHAR,
  telephone VARCHAR,
  website VARCHAR,
  description TEXT,
  created_at TIMESTAMP DEFAULT current_timestamp
);

CREATE TABLE api_keys (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INT,
  created_at TIMESTAMP DEFAULT current_timestamp,
  usages_left INT DEFAULT 1000,
  is_expired BOOLEAN DEFAULT FALSE,
  key_type VARCHAR DEFAULT 'general'
);

COMMENT ON COLUMN api_keys.key_type IS '[general, topic, sources]';

ALTER TABLE api_keys ADD FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE users ADD FOREIGN KEY (company_id) REFERENCES companies (id);


