CREATE TABLE "requests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "timestamp" timestamp,
  "company_id" int,
  "user_id" varchar,
  "chat_id" varchar,
  "raw_text" text,
  "filter_id" int,
  "timestamp_filter" timestamp,
  "parent_id" int,
  "status" varchar
);

CREATE TABLE "responses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "timestamp" timestamp,
  "request_id" int,
  "raw_text" text
);

CREATE TABLE "feedbacks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "respons_id" int,
  "user_id" varchar,
  "timestamp" timestamp,
  "estimation" int,
  "note" text
);

CREATE TABLE "filtering_rules" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp,
  "company_id" int,
  "user_id" varchar,
  "word" varchar,
  "description" text,
  "is_archive" bool,
  "archive_at" timestamp
);

CREATE TABLE "companies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar,
  "telephone" varchar,
  "website" varchar,
  "description" text,
  "created_at" timestamp DEFAULT (now()),
  "is_disabled" boolean DEFAULT false
);

CREATE TABLE "api_keys" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" int,
  "key_id" varchar,
  "created_at" timestamp DEFAULT (now()),
  "expired_at" timestamp,
  "usages_left" int DEFAULT 1000,
  "is_disabled" bool DEFAULT false,
  "key_type" varchar DEFAULT 'general'
);

COMMENT ON COLUMN "api_keys"."key_type" IS '[general, topic, sources]';

ALTER TABLE "requests" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id");

ALTER TABLE "requests" ADD FOREIGN KEY ("parent_id") REFERENCES "requests" ("id");

ALTER TABLE "responses" ADD FOREIGN KEY ("request_id") REFERENCES "requests" ("id");

ALTER TABLE "feedbacks" ADD FOREIGN KEY ("respons_id") REFERENCES "responses" ("id");

ALTER TABLE "filtering_rules" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id");

ALTER TABLE "api_keys" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id");
