version: "3.9"
services:
  ml:
#    build: ./fastapi_app
    image: mar1a/msk23:base
#    deploy:
#      resources:
#        limits:
#          cpus: '0.80'
#          memory: 12g
    restart: unless-stopped
    ports:
      - "8000:8000"
    container_name: fastapi
    environment:
      PORT: 8000
    volumes:
      - C:/logs/fastapi/:/logs/
    networks:
      - test

  postgres_db:
    image: "postgres:12"
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: "msk23"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    container_name: postgres_db
    networks:
      - test

networks:
  test: